src/objects/book__c.object
<CustomObject>
    <fields>
        <fullName>author__c</fullName>
        <label>author</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>edition__c</fullName>
        <label>edition</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>price__c</fullName>
        <label>price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>book</label>
    <nameField>
        <label>book_name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>books</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Batchap.cls
global class Batchap implements Database.Batchable<Book__c>{
    
   global Iterable<book__c> start(Database.BatchableContext bc) {
    
   list<book__c> blist=new list<book__c>([select name,edition__c,author__c,price__c from book__c]);
    
        return blist;
    
    }
   global void execute(Database.BatchableContext bc, LIST<book__c> blist){
    
        for(book__c b:blist){
            b.price__c=109;
            update b;
        }    
    
    
    }
    
    global void finish(Database.BatchableContext bc) {
    
    }
}