src/objects/book__c.object
<CustomObject>
    <fields>
        <fullName>author__c</fullName>
        <label>author</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>edition__c</fullName>
        <label>edition</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>price__c</fullName>
        <label>price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>book</label>
    <nameField>
        <label>book_name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>books</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/reccls.cls
public with sharing class reccls {
    
    public string recid{get; set;}
    
    public PageReference delrecord() {
        System.debug('------'+recid);
        Account acc=[select id,name from Account where id=:recid];
        delete acc;
        PageReference pr=new PageReference('/apex/jscript6');
        pr.setredirect(true);
        return pr;
    }


    public list<contact> clist { get; set; }

    public  list<Account> alist{ get; set; }

    public list<book__c> blist{ get; set; }
    
    public reccls(){
        blist=[select name,price__c,author__c,edition__c from book__c];
        alist=[select name,phone from Account];
        clist=[select name,mobilephone from contact];
        }
    
}