src/objects/department__c.object
<CustomObject>
    <label>department</label>
    <nameField>
        <displayFormat>d-{000}</displayFormat>
        <label>dept no</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/employees__c.object
<CustomObject>
    <description>emp details</description>
    <fields>
        <fullName>department__c</fullName>
        <label>department</label>
        <referenceTo>department__c</referenceTo>
        <relationshipLabel>employees</relationshipLabel>
        <relationshipName>employees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>e_name__c</fullName>
        <label>e.name</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>employee</label>
    <nameField>
        <displayFormat>e-{000}</displayFormat>
        <label>e.no</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/mylist.cls
public  class mylist {
public void m1(){
list<department__c> dl=[select id,name,(select id,e_name__c from employees__r) from department__c];
//map<id,list<employees__c>> mp=new map<id,list<employees__c>>();
for(department__c d:dl){
   // mp.put(d.id,d);
    System.debug('@@@@@@@@@@@@@@@@@@@@---record is '+d);
    //System.debug('@@@@@@@@@@@@@@@@@@@@---id is '+d.id);
}
   // System.debug('*********************-----record are '+mp.values());
    //System.debug('*********************--------id are'+mp.keyset());
}
}