src/objects/employees__c.object
<CustomObject>
    <description>emp details</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>employees</relationshipLabel>
        <relationshipName>employees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>employee</label>
    <nameField>
        <displayFormat>e-{000}</displayFormat>
        <label>e.no</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/sample6cls.cls
public class sample6cls {
    public employees__c emp{get;set;}
    public Account objacc{get;set;}
    
    public sample6cls(ApexPages.StandardController controller) {
    
        emp = (employees__c)controller.getRecord();
        System.debug('===================>'+emp);
        //System.debug('===================>'+this.emp);
    
    }
    public void somemethod(){
     objacc=[select name from account where id=:emp.Account__c limit 1];
    System.debug('========>>>>>>'+objacc);
    }

}